config/routes.rb
Rails.application.routes.draw do
  root "queries#index"
  resources :queries, except: [ :edit, :update ]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/query.rb
class Query < ApplicationRecord
  validates :start, :end, :respondent, presence: true
  enum :respondent, [ "PJM", "PGE", "PACW", "CISO", "DUK", "ERCO", "MISO", "TVA", "NYIS", "FPL" ]
end

app/models/query_service.rb
class QueryService
  attr :query

  def initialize(query: nil)
    raise ArgumentError if query.nil?
    @query = query
  end

  def call
    puts @query

    connection = Faraday.new({
      url: "https://api.eia.gov/v2/electricity/rto/daily-fuel-type-data/data",
      params: {
        api_key: "R3BY2bN0rjde1WYXicc41vuBo6YMeOfkYZEU6FOt"
      },
      headers: {
        'X-Params': {
          frequency: "daily",
          data: [ "value" ],
          facets: {
            timezone: [ "Eastern" ],
            respondent: [ "PJM" ]
          },
          start: "2024-03-01",
          end: "2024-03-03",
          sort: [ {
            column: "period",
            direction: "desc"
          } ],
          offset: 0,
          length: 5000
        }.to_json()
      }
    })

    connection.get()
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def index
    @queries = Query.all
  end

  def show
    # TODO: replace with queried data
    # TODO: refactor into a decorator object
    @query = Query.find params[:id]
    queried_data = JSON.parse(File.read("data.json"))["response"]["data"]
    dataframe = Daru::DataFrame.new(queried_data)

    @fueltypes = dataframe["fueltype"].uniq.to_a
    @usage_by_type = {}

    @fueltypes.each do |type|
      @usage_by_type[type] = dataframe.where(
        dataframe["fueltype"].in([ type ])
      ).to_json
    end
  end

  def create
    respondent = Query.respondents[params[:respondent]]
    clean_params[:respondent] = respondent
    @query = Query.new(clean_params)

    if @query.save
      # TODO: query API data from EIA
      # QueryService.new(query: @query).call

      redirect_to query_path(@query)
    else
      flash[:error] = @query.errors.full_messages
      render :new
    end
  end

  def new
    @query = Query.new()
  end

  private

  def clean_params
    params.require(:query).permit(:start, :end)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Utility Dashboard Demo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    >
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/queries/index.html.erb
<h1>Queries</h1>

<ul>
  <% @queries.each do |query| %>
    <li>
      <%= link_to "#{query.respondent}, from #{query.start} to #{query.end}",
      query_path(query) %>
    </li>
  <% end %>
</ul>

<%= link_to "New Query", new_query_path %>

app/views/queries/new.html.erb
<h1 class="mb-3">New Query</h1>

<% if flash[:error] %>
  <h2>
    <ul>
      <% flash[:error].each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </h2>
<% end %>

<%= form_with model: @query do |form| %>
  <div class="mb-3">
    <%= form.label :respondent, "Respondent", class: "form-label" %>
    <%= form.select :respondent, Query.respondents, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :start, "Start Date YYYY-MM-DD", class: "form-label" %>
    <%= form.text_field :start, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :end, "End Date YYYY-MM-DD", class: "form-label" %>
    <%= form.text_field :end, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/queries/show.html.erb
<h1>
  Querying
  <%= @query.respondent %>
  from
  <%= @query.start %>
  to
  <%= @query.end %>
</h1>

<div>
  <canvas id="myChart"></canvas>
</div>

<script>
  const ctx = document.getElementById('myChart');
  const data = {
    datasets: [
      <% @usage_by_type.each do |key, value| %>
        {
          label: "<%= key %>",
          data: <%= value.html_safe %>
        },
      <% end %>
    ]
  };

  const config = {
  type: 'bar',
  data: data,
  options: {
    parsing: {
      xAxisKey: "period",
      yAxisKey: "value",
    },
    plugins: {
      title: {
        display: true,
        text: 'Fuel types generated from <%= @query.start %> to <%= @query.end %>'
      },
    },
    responsive: true,
    scales: {
      x: {
        stacked: true,
      },
      y: {
        stacked: true
      }
    }
  }
};

  new Chart(ctx, config);
</script>